CREATE TABLE IF NOT EXISTS `teste`.`USUARIO` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NOME` VARCHAR(255) NOT NULL,
  `USER_TELEFONE` VARCHAR(45) NOT NULL,
  `USER_SENHA` VARCHAR(45) NOT NULL,
  `USER_EMAIL` VARCHAR(45) NOT NULL,
  `USER_FOTO` BLOB NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`PROFESSOR` (
  `PROF_ID` INT NOT NULL AUTO_INCREMENT,
  `PROF_SIAPE` VARCHAR(45) NOT NULL,
  `PROF_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PROF_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`ALUNO` (
  `ALUN_ID` INT NOT NULL AUTO_INCREMENT,
  `ALUN_MATRICULA` VARCHAR(45) NOT NULL,
  `ALUN_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ALUN_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`VISITANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`VISITANTE` (
  `VISI_ID` INT NOT NULL AUTO_INCREMENT,
  `VISI_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VISI_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`PERFIL` (
  `USUARIO_USER_ID` INT NULL,
  `PROFESSOR_PROF_ID` INT NULL,
  `ALUNO_ALUN_ID` INT NULL,
  `VISITANTE_VISI_ID` INT NULL,
  `PERFIL_ID` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_table1_USUARIO_idx` (`USUARIO_USER_ID` ASC) VISIBLE,
  INDEX `fk_PERFIL_PROFESSOR1_idx` (`PROFESSOR_PROF_ID` ASC) VISIBLE,
  INDEX `fk_PERFIL_ALUNO1_idx` (`ALUNO_ALUN_ID` ASC) VISIBLE,
  INDEX `fk_PERFIL_VISITANTE1_idx` (`VISITANTE_VISI_ID` ASC) VISIBLE,
  PRIMARY KEY (`PERFIL_ID`),
  CONSTRAINT `fk_table1_USUARIO`
    FOREIGN KEY (`USUARIO_USER_ID`)
    REFERENCES `teste`.`USUARIO` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERFIL_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_PROF_ID`)
    REFERENCES `teste`.`PROFESSOR` (`PROF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERFIL_ALUNO1`
    FOREIGN KEY (`ALUNO_ALUN_ID`)
    REFERENCES `teste`.`ALUNO` (`ALUN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERFIL_VISITANTE1`
    FOREIGN KEY (`VISITANTE_VISI_ID`)
    REFERENCES `teste`.`VISITANTE` (`VISI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`AGENDAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`AGENDAMENTO` (
  `AGEN_ID` INT NOT NULL AUTO_INCREMENT,
  `AGEN_DATA` DATETIME NOT NULL,
  `PERFIL_PERFIL_ID1` INT NOT NULL,
  `PERFIL_PERFIL_ID2` INT NOT NULL,
  PRIMARY KEY (`AGEN_ID`),
  INDEX `fk_AGENDAMENTO_PERFIL1_idx` (`PERFIL_PERFIL_ID1` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTO_PERFIL2_idx` (`PERFIL_PERFIL_ID2` ASC) VISIBLE,
  CONSTRAINT `fk_AGENDAMENTO_PERFIL1`
    FOREIGN KEY (`PERFIL_PERFIL_ID1`)
    REFERENCES `teste`.`PERFIL` (`PERFIL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTO_PERFIL2`
    FOREIGN KEY (`PERFIL_PERFIL_ID2`)
    REFERENCES `teste`.`PERFIL` (`PERFIL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
